name: Criar EXE do Alarme

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:

  build:

    runs-on: windows-latest

    steps:

      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Criar EXE
        run: npm run dist

      - name: Salvar EXE
        uses: actions/upload-artifact@v4
        with:
          name: Alarme-de-Tempo-Windows
          path: |
            dist/*.exe
